### ISSUE TITLE
Custom Mode...

### ISSUE THREAD

**Issue by MaoSuYu** [JesseGuoX/GPT-Translator#1]
I have been using this translation program for a while, but during this period OpenAI has released many new models, but currently only gpt3.5 and gpt4 can be selected. Can the options for custom models be added? Also, is it possible to compile a universal version that supports the M series chips?

**Comment by MaoSuYu** [comment]
<img width="400" alt="symao2024-07-25 10 09 46" src="https://github.com/user-attachments/assets/a6c48468-0dc9-487b-9937-3862c9b3e40c">

**Comment by MaoSuYu** [comment]
<img width="340" alt="symao2024-07-25 10 10 23" src="https://github.com/user-attachments/assets/baf59570-4257-4d3d-bf87-163ac404d59d">
I hope to add a custom model filling selection, thank you very much if possible.

**Comment by JesseGuoX** [comment]
@MaoSuYu Thank you for using this software. Unfortunately, I currently do not have much time to maintain this project. I recommend using the [Photon AI Translator ](https://apps.apple.com/us/app/photon-ai-translator/id6446066013) instead.❤

**Comment by MaoSuYu** [comment]
I am currently using the Photon AI Translator, and I find its features to be extremely helpful. Thank you!🙏
